// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Core.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MUSTERIAD");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MUSTERISOYAD");

                    b.Property<string>("OdemeAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ODEME_ACK");

                    b.Property<int>("OdemeDurumu")
                        .HasColumnType("int")
                        .HasColumnName("ODEME_KD");

                    b.Property<int>("OdemeNo")
                        .HasColumnType("int")
                        .HasColumnName("ODEMENO");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("date")
                        .HasColumnName("ODEME_TR");

                    b.Property<decimal>("OdenecekTutar")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("ODENECEK_TTR");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TCKIMLIKNO");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NYO_SOSYALYARDİM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 3, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(675),
                            MusteriAd = "Ayşe",
                            MusteriSoyad = "Yılmaz",
                            OdemeAciklama = "Ürün satışı",
                            OdemeDurumu = 0,
                            OdemeNo = 0,
                            OdemeTarihi = new DateTime(2023, 7, 19, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(665),
                            OdenecekTutar = 500.00m,
                            TcKimlikNo = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 3, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(678),
                            MusteriAd = "Mehmet",
                            MusteriSoyad = "Kaya",
                            OdemeAciklama = "Hizmet ödemesi",
                            OdemeDurumu = 1,
                            OdemeNo = 0,
                            OdemeTarihi = new DateTime(2023, 7, 4, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(677),
                            OdenecekTutar = 750.50m,
                            TcKimlikNo = "23456789012"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 3, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(680),
                            MusteriAd = "Elif",
                            MusteriSoyad = "Demir",
                            OdemeAciklama = "Fatura ödemesi",
                            OdemeDurumu = 0,
                            OdemeNo = 0,
                            OdemeTarihi = new DateTime(2023, 7, 27, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(679),
                            OdenecekTutar = 300.00m,
                            TcKimlikNo = "34567890123"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 3, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(682),
                            MusteriAd = "Ahmet",
                            MusteriSoyad = "Yıldız",
                            OdemeAciklama = "Kira ödemesi",
                            OdemeDurumu = 2,
                            OdemeNo = 0,
                            OdemeTarihi = new DateTime(2023, 6, 4, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(681),
                            OdenecekTutar = 1200.75m,
                            TcKimlikNo = "45678901234"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 8, 3, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(684),
                            MusteriAd = "Zeynep",
                            MusteriSoyad = "Akgün",
                            OdemeAciklama = "Alışveriş ödemesi",
                            OdemeDurumu = 1,
                            OdemeNo = 0,
                            OdemeTarihi = new DateTime(2023, 7, 12, 16, 31, 16, 865, DateTimeKind.Local).AddTicks(683),
                            OdenecekTutar = 250.25m,
                            TcKimlikNo = "56789012345"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
